feat: added lead appender task
theproductiveprogrammer/desktop-avatar-plugins pull request #26
Opened 2022-06-28 08:36 UTC by arunp7

2022-06-28 11:48 UTC, theproductiveprogrammer requested changes

2022-06-28 11:48 UTC, theproductiveprogrammer commented on NAVIGATOR_LEAD_APPENDER.js
> +            console.log('1')
Missed in your clean up (console.log(1))

2022-06-28 11:48 UTC, theproductiveprogrammer commented on NAVIGATOR_LEAD_APPENDER.js
> +        names => names.map(name => name.innerText))
Nice technique

2022-06-28 11:48 UTC, theproductiveprogrammer commented on NAVIGATOR_LEAD_APPENDER.js
> +            let updtd_date = new Date(updtd_date_ele)
Are we assuming here that `new Date()` can parse all date types? Would suggest using a library like `day.js` and several defined formats

2022-06-28 11:48 UTC, theproductiveprogrammer commented on NAVIGATOR_LEAD_APPENDER.js
> +            if(updtd_date >= i_date)
This is a tricky one - what about leads added on the same date? How do we not duplicate them?

2022-06-28 11:53 UTC, arunp7 commented on NAVIGATOR_LEAD_APPENDER.js
> +            console.log('1')
oh ! Will correct Charles.

2022-06-28 11:54 UTC, arunp7 commented on NAVIGATOR_LEAD_APPENDER.js
> +        names => names.map(name => name.innerText))
Thanks Charles.

2022-06-28 12:08 UTC, arunp7 commented on NAVIGATOR_LEAD_APPENDER.js
> +            if(updtd_date >= i_date)
I thought about that, we will have to add some kind of logic in the backend (linkedin url is only the unique thing that we could check for duplicate with the data we have) or else we will have to add some input variables

2022-07-06 06:47 UTC, theproductiveprogrammer approved these changes

2022-07-06 06:47 UTC, merged